spring.application.name=Urlshorten
spring.datasource.url=jdbc:postgresql://localhost:5433/urlshortener
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
server.port=8081
